import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { useEffect, useState } from "react";
import { fetchClient } from "./_client";
import Link from "next/link";

const request = fetchClient();

type Post = {
  Post_id: string;
  Created_at: string;
  Lat: any;
  Lon: any;
  Subject: string;
  Description: string;
  Author: string;
};

export default function Home() {
  const [posts, setPosts] = useState<Post[]>([]);

  useEffect(() => {
    request
      .get("suggestions?lat=51.51&lon=-0.08")
      .then((res) => {
        setPosts(res.data);
      })
      .catch((err) => {
        console.log(err);
      });
  }, []);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.suggestions}>
          {posts.map((post, idx) => (
            <Link
              className={styles.post_card}
              key={idx}
              href={`post/${post.Post_id}`}
            >
              <div className={styles.content}>
                <h2 className={styles.subject}>{post.Subject}</h2>
                <p className={styles.description}>{post.Description}</p>
              </div>
              <div className={styles.footer}>
                <h4 className={styles.author}>{post.Author}</h4>
                <h4 className={styles.created_at}>
                  {new Date(post.Created_at).toLocaleDateString([])}
                </h4>
              </div>
            </Link>
          ))}
        </div>
      </main>
    </>
  );
}
